### ISSUE TITLE
 Cannot find module node_modules\cordova-uglify\node_modules\uglify-js

### ISSUE THREAD

**Issue by mattalco** [rossmartin/cordova-uglify#19]
I am having the same issue as this person: https://github.com/rossmartin/cordova-uglify/issues/18

However, I've tried following all the steps in #18 but have not been successful in solving the problem.

Upon installation, I receive this response. I'm not sure why, but only imagemin is added to the directory `node_modules\cordova-uglify\node_modules`

![image](https://cloud.githubusercontent.com/assets/13972013/13333532/82fb2e56-dbd5-11e5-8e7d-5e9c6c65a5bd.png)
 
My package.json includes the correct dependencies, but they aren't in the directory that this new version cordova-uglify seems to be searching.

**Comment by hessius** [comment]
+1, changing all the require lines to remove path.join(dependencyPath, fixes the issue

**Comment by rossmartin** [comment]
I'm a bit late to this, will be looking into tomorrow.  Are you running on Windows?

**Comment by rossmartin** [comment]
@hessius 

That will work but it won't for him because not all of the modules are being added to `node_modules\cordova-uglify\node_modules`

You should be seeing these modules in your `${project}/node_modules/cordova-uglify/node_modules `folder - 
![screen shot 2016-02-25 at 11 29 57 pm](https://cloud.githubusercontent.com/assets/2498502/13344033/e370dc80-dc17-11e5-9841-9b298f80f15f.png)

**Comment by mattalco** [comment]
Running Windows 7.

Correct - they aren't being added to that directory for some reason.

I ended up solving this by removing them from my package.json - which confused me a bit since I thought NPM started requiring everyone in V3 to explicitly list their dependencies.

**Comment by JeremyColton** [comment]
HI, I'm running on a Mac. using:
iOS v 4.0.1
cli v5.4.1

From my project root, I ran:
sudo npm install cordova-uglify

I then have the directory layout above described by rossmartin.

From my project root, I run:
cordova prepare ios

I see this error message:
Cannot find module 'Users/jeremy/my_xcode_apps/<my app>/node_modules/uglify-js' but this is because the last folder doesn't exist, it's called 'cordova-uglify'.

I've tried uninstalling and re-installing and I see the same error as I described!

What am I missing?

**Comment by JeremyColton** [comment]
I updated /hooks/after_prepare/uglify.js, line 9
instead of 'node_modules', I changed it to 'node_modules/cordova_uglify/node_modules'

Now it works!

**Comment by hessius** [comment]
@jeremycolton maybe you could submit a PR?

**Comment by NileshSystematix** [comment]
@JeremyColton But I am facing same issue. Can you please help me

**Comment by JeremyColton** [comment]
@NileshSystematix I wrote the fix in my comment on 18 Feb... this doesn't work for you?

**Comment by NileshSystematix** [comment]
@JeremyColton I is not working for me

**Comment by JeremyColton** [comment]
@NileshSystematix so I suggest you add debug statements to this file:
 /hooks/after_prepare/uglify.js

This will show you why it's failing. You can then fix the bug :)
