### ISSUE TITLE
Make ugifly.js configurable

### ISSUE THREAD

**Issue by ygayl** [rossmartin/cordova-uglify#8]
Hi,

Wouldn't be useful to be able to use a configuration file for setting the folder to process, specify the cssMinifier, set ngAnnotate (true or false), etc.

I can see that those are hardcoded within the uglify.js file and I think that it will be very usefull to have it over configuration (with default values).

Please let me know what you think and we can have a look to it together if you want (via pull request?) :)

Best,
Yassine

**Comment by rossmartin** [comment]
Yassine,

Thanks for opening this I have planned on adding this functionality but I've been really busy with a new job since April.  I haven't been using Cordova and Ionic as often unfortunately.  

If I don't add the functionality before this Sunday I'll let you know and a pull request with it would be awesome.

Thank you.

**Comment by rossmartin** [comment]
Added via https://github.com/rossmartin/cordova-uglify/commit/2c9d939d3ad4da93c5b7604d8fa82f0b9a5f2139 and https://github.com/rossmartin/cordova-uglify/commit/1aba4bf0dd44f5b3bdb2134193799784b520c1b7
